import type { LiteratureRecord, OutlineNode } from '../../shared/contracts'

const now = () => new Date().toISOString()

export const demoLiterature: LiteratureRecord[] = [
  {
    id: 'lit-openalex-01',
    projectId: 'project-demo',
    title: 'Generative Artificial Intelligence in Higher Education: Evidence and Emerging Practices',
    authors: ['L. Chen', 'M. Rossi'],
    year: 2024,
    venue: 'Computers & Education: Artificial Intelligence',
    abstract: '围绕生成式人工智能在高等教育中的应用场景、教学收益与学术诚信风险进行综述。',
    source: 'demo',
    included: true,
    origin: 'demo',
    verificationStatus: 'demo',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'lit-openalex-02',
    projectId: 'project-demo',
    title: 'Human–AI Collaborative Writing: A Systematic Review of Learning Outcomes',
    authors: ['S. Patel', 'Y. Wang', 'A. Martin'],
    year: 2023,
    venue: 'Educational Technology Research and Development',
    abstract: '梳理人机协同写作对反馈效率、写作信心和高阶认知活动的影响。',
    source: 'demo',
    included: true,
    origin: 'demo',
    verificationStatus: 'demo',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'lit-openalex-03',
    projectId: 'project-demo',
    title: 'Academic Integrity in the Age of Large Language Models',
    authors: ['R. Williams', 'J. K. Lee'],
    year: 2024,
    venue: 'Assessment & Evaluation in Higher Education',
    abstract: '讨论大语言模型带来的作者身份、引用真实性和过程性评价问题。',
    source: 'demo',
    included: false,
    origin: 'demo',
    verificationStatus: 'demo',
    createdAt: now(),
    updatedAt: now(),
  },
]

export const demoOutline: OutlineNode[] = [
  {
    id: 'outline-01',
    title: '一、绪论',
    level: 1,
    objective: '说明研究背景、问题与研究价值',
    targetWords: 1200,
    citationIds: ['lit-openalex-01'],
    children: [
      {
        id: 'outline-01-01',
        title: '1.1 研究背景与问题提出',
        level: 2,
        objective: '交代高校写作教学的数字化转型背景并提出核心问题',
        targetWords: 650,
        citationIds: ['lit-openalex-01'],
        children: [
          {
            id: 'outline-01-01-01',
            title: '1.1.1 高校写作教学的数字化转型',
            level: 3,
            objective: '说明写作教学从结果评价向过程支持转变的现实需求',
            targetWords: 320,
            citationIds: ['lit-openalex-01'],
            children: [],
          },
          {
            id: 'outline-01-01-02',
            title: '1.1.2 生成式 AI 带来的新问题',
            level: 3,
            objective: '提出反馈效率、写作主体性和学术诚信之间的张力',
            targetWords: 330,
            citationIds: ['lit-openalex-01', 'lit-openalex-03'],
            children: [],
          },
        ],
      },
      {
        id: 'outline-01-02',
        title: '1.2 研究目标与研究价值',
        level: 2,
        objective: '明确研究问题、理论价值与实践价值',
        targetWords: 550,
        citationIds: ['lit-openalex-01'],
        children: [
          {
            id: 'outline-01-02-01',
            title: '1.2.1 研究问题与分析思路',
            level: 3,
            objective: '说明研究围绕作用机制、风险边界与治理路径展开',
            targetWords: 280,
            citationIds: [],
            children: [],
          },
          {
            id: 'outline-01-02-02',
            title: '1.2.2 理论价值与实践价值',
            level: 3,
            objective: '说明研究对人机协同写作理论和教学设计的意义',
            targetWords: 270,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'outline-02',
    title: '二、理论基础与研究现状',
    level: 1,
    objective: '界定人机协同写作并总结已有研究',
    targetWords: 1800,
    citationIds: ['lit-openalex-01', 'lit-openalex-02'],
    children: [
      {
        id: 'outline-02-01',
        title: '2.1 核心概念界定',
        level: 2,
        objective: '界定生成式人工智能与人机协同写作',
        targetWords: 600,
        citationIds: ['lit-openalex-01', 'lit-openalex-02'],
        children: [
          {
            id: 'outline-02-01-01',
            title: '2.1.1 生成式人工智能',
            level: 3,
            objective: '界定生成式人工智能在教学情境中的能力边界',
            targetWords: 300,
            citationIds: ['lit-openalex-01'],
            children: [],
          },
          {
            id: 'outline-02-01-02',
            title: '2.1.2 人机协同写作',
            level: 3,
            objective: '区分辅助写作、协同写作与替代写作',
            targetWords: 300,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
        ],
      },
      {
        id: 'outline-02-02',
        title: '2.2 理论基础',
        level: 2,
        objective: '构建解释生成式 AI 教学作用的理论框架',
        targetWords: 650,
        citationIds: ['lit-openalex-02'],
        children: [
          {
            id: 'outline-02-02-01',
            title: '2.2.1 学习支架理论',
            level: 3,
            objective: '解释提示、示例和反馈如何形成动态学习支架',
            targetWords: 330,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
          {
            id: 'outline-02-02-02',
            title: '2.2.2 自我调节学习理论',
            level: 3,
            objective: '解释目标设定、监控与反思在写作过程中的作用',
            targetWords: 320,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
        ],
      },
      {
        id: 'outline-02-03',
        title: '2.3 国内外研究述评',
        level: 2,
        objective: '总结现有研究进展并识别证据缺口',
        targetWords: 550,
        citationIds: ['lit-openalex-01', 'lit-openalex-02', 'lit-openalex-03'],
        children: [
          {
            id: 'outline-02-03-01',
            title: '2.3.1 研究进展与主要发现',
            level: 3,
            objective: '归纳生成式 AI 在反馈与写作支持方面的已有证据',
            targetWords: 280,
            citationIds: ['lit-openalex-01', 'lit-openalex-02'],
            children: [],
          },
          {
            id: 'outline-02-03-02',
            title: '2.3.2 现有研究的不足',
            level: 3,
            objective: '指出长期效果、主体性和过程证据方面的不足',
            targetWords: 270,
            citationIds: ['lit-openalex-03'],
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'outline-03',
    title: '三、生成式 AI 介入高校写作的作用机制',
    level: 1,
    objective: '分析反馈、支架与反思三个作用路径',
    targetWords: 2400,
    citationIds: ['lit-openalex-02'],
    children: [
      {
        id: 'outline-03-01',
        title: '3.1 即时反馈机制',
        level: 2,
        objective: '分析生成式 AI 如何缩短反馈循环',
        targetWords: 800,
        citationIds: ['lit-openalex-02'],
        children: [
          {
            id: 'outline-03-01-01',
            title: '3.1.1 语言表达反馈',
            level: 3,
            objective: '说明语言层面反馈对修订效率的影响',
            targetWords: 400,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
          {
            id: 'outline-03-01-02',
            title: '3.1.2 论证结构反馈',
            level: 3,
            objective: '说明结构反馈如何支持论点与证据对齐',
            targetWords: 400,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
        ],
      },
      {
        id: 'outline-03-02',
        title: '3.2 认知支架机制',
        level: 2,
        objective: '分析问题分解、材料组织和论证提示的支架作用',
        targetWords: 800,
        citationIds: ['lit-openalex-01', 'lit-openalex-02'],
        children: [
          {
            id: 'outline-03-02-01',
            title: '3.2.1 复杂任务分解',
            level: 3,
            objective: '说明任务分解如何降低写作过程中的认知负荷',
            targetWords: 400,
            citationIds: ['lit-openalex-01'],
            children: [],
          },
          {
            id: 'outline-03-02-02',
            title: '3.2.2 材料组织与论证提示',
            level: 3,
            objective: '说明材料组织提示如何辅助形成可检验论证',
            targetWords: 400,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
        ],
      },
      {
        id: 'outline-03-03',
        title: '3.3 元认知反思机制',
        level: 2,
        objective: '分析比较、质疑与迭代如何促进写作反思',
        targetWords: 800,
        citationIds: ['lit-openalex-02'],
        children: [
          {
            id: 'outline-03-03-01',
            title: '3.3.1 多方案比较与判断',
            level: 3,
            objective: '说明多方案比较如何促进判断标准显性化',
            targetWords: 400,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
          {
            id: 'outline-03-03-02',
            title: '3.3.2 修订过程中的自我监控',
            level: 3,
            objective: '说明过程记录如何支持自我监控与反思',
            targetWords: 400,
            citationIds: ['lit-openalex-02'],
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'outline-04',
    title: '四、风险、边界与教学治理',
    level: 1,
    objective: '讨论引用、学术诚信与评价机制',
    targetWords: 1800,
    citationIds: ['lit-openalex-03'],
    children: [
      {
        id: 'outline-04-01',
        title: '4.1 主要风险与使用边界',
        level: 2,
        objective: '识别引用失真、能力替代和隐私等风险',
        targetWords: 900,
        citationIds: ['lit-openalex-03'],
        children: [
          {
            id: 'outline-04-01-01',
            title: '4.1.1 引用失真与事实幻觉',
            level: 3,
            objective: '分析不可追溯引用和事实错误的形成与后果',
            targetWords: 450,
            citationIds: ['lit-openalex-03'],
            children: [],
          },
          {
            id: 'outline-04-01-02',
            title: '4.1.2 写作主体性与能力替代',
            level: 3,
            objective: '分析过度依赖对写作判断与能力发展的影响',
            targetWords: 450,
            citationIds: ['lit-openalex-03'],
            children: [],
          },
        ],
      },
      {
        id: 'outline-04-02',
        title: '4.2 教学治理路径',
        level: 2,
        objective: '提出过程留痕、引用核验与多元评价策略',
        targetWords: 900,
        citationIds: ['lit-openalex-03'],
        children: [
          {
            id: 'outline-04-02-01',
            title: '4.2.1 过程留痕与引用核验',
            level: 3,
            objective: '建立写作过程记录和引用证据核验机制',
            targetWords: 450,
            citationIds: ['lit-openalex-03'],
            children: [],
          },
          {
            id: 'outline-04-02-02',
            title: '4.2.2 人机协同评价机制',
            level: 3,
            objective: '构建兼顾结果、过程与反思质量的评价方式',
            targetWords: 450,
            citationIds: ['lit-openalex-03'],
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 'outline-05',
    title: '五、结论与展望',
    level: 1,
    objective: '总结发现并提出后续研究方向',
    targetWords: 800,
    citationIds: [],
    children: [
      {
        id: 'outline-05-01',
        title: '5.1 研究结论',
        level: 2,
        objective: '归纳作用机制、风险边界与治理建议',
        targetWords: 450,
        citationIds: [],
        children: [
          {
            id: 'outline-05-01-01',
            title: '5.1.1 主要发现',
            level: 3,
            objective: '回应研究问题并概括主要发现',
            targetWords: 450,
            citationIds: [],
            children: [],
          },
        ],
      },
      {
        id: 'outline-05-02',
        title: '5.2 研究局限与未来展望',
        level: 2,
        objective: '说明证据边界并提出未来实证研究方向',
        targetWords: 350,
        citationIds: [],
        children: [
          {
            id: 'outline-05-02-01',
            title: '5.2.1 局限与后续研究方向',
            level: 3,
            objective: '提出长期追踪、跨学科比较和真实教学实验方向',
            targetWords: 350,
            citationIds: [],
            children: [],
          },
        ],
      },
    ],
  },
]
